### ISSUE TITLE
Reading with python, username and password text data from Nextion

### ISSUE THREAD

**Issue by javed222** [yozik04/nextion#13]
Hello!
I am trying to read in python, text data from nextion for validate user and password information.
Pressing button b0.txt, send from t0.txt “hello”

![Captura](https://user-images.githubusercontent.com/28707380/93132553-41627200-f6ac-11ea-82df-4065e34d4ba3.PNG)
 
In raspberry pi can see two messages:
1. Touch event
2. Message of data text from Nextion

How I can retrieve data text message in a variable with your python client?
Thanks
Javier

**Comment by yozik04** [comment]
Hello.
Simple. You register an event handler on a button.
When the button is touched you do ‘val = await nextion.get(“t0.txt”)’

**Comment by javed222** [comment]
Hello!! Thanks 

if I do this:

![Captura](https://user-images.githubusercontent.com/28707380/93214422-8b466900-f73b-11ea-96f8-4caba87e93a9.PNG)

have this error:
![Captura](https://user-images.githubusercontent.com/28707380/93214567-b9c44400-f73b-11ea-8413-37f214fcc873.PNG)

please tell me what i have to do

thank you very much!!
Javier

**Comment by javed222** [comment]
also try this:

![Captura](https://user-images.githubusercontent.com/28707380/93216528-3eb05d00-f73e-11ea-8cc3-c82a886c66a9.PNG)

and have this error:

![Captura](https://user-images.githubusercontent.com/28707380/93216766-83d48f00-f73e-11ea-9c77-9622eeb9bfe9.PNG)

i am lost with this
Thanks
Javier

**Comment by yozik04** [comment]
Second approach is right. One mistake: not ‘nextion’ but ‘client’ in your case and define it somewhere in the module level.

Jevgeni

**Comment by javed222** [comment]
Thanks Jevgeni!!
just one doubt

I rename "nextion" to "client", but client is not declared yet...
Please where i must declare client?

Thank you so much for everything
Javier

**Comment by yozik04** [comment]
Make this variable global. A search engine will help 😅

Jevgeni

**Comment by javed222** [comment]
you are right
sorry

**Comment by javed222** [comment]
Thank you Jevgeni!!
All is right now
Javier
