### ISSUE TITLE
Can not load firmware

### ISSUE THREAD

**Issue by CharlesGodwin** [yozik04/nextion#14]
I have a program running successfully using the Nextion on /dev/ttyS0 and baud rate 9600. It does not use your software but uses pyserial.

I installed this software, version 1.6.1, and am trying to use it to upload firmware. But when I run `nextion-fw-upload -b 9600 /dev/ttyS0 homedata.tft` I always get `nextion.exceptions.ConnectionFailed: No baud rate suited` after it runs through the available choices. I terminate the other program before I run this program. 

Am I doing something wrong?

Thanks

**Comment by yozik04** [comment]
Hi Charles,
Looks like you do everything right. Please post a longer debug log.
This uploading is more in beta stage. But in your case it looks like it fails before upload even starts.
