### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by oldtimerflyer** [yozik04/nextion#15]
Like to explore and use this library but can get it installed.
Any idea what is going wrong?

KR.

pi@raspberrypi:~ $ pip install nextion==1.6.1
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting nextion==1.6.1
  Could not find a version that satisfies the requirement nextion==1.6.1 (from versions: )
No matching distribution found for nextion==1.6.1

**Comment by yozik04** [comment]
`pip3 install nextion` ?

**Comment by oldtimerflyer** [comment]
Great ! Thank you.
