### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by dezfutak** [yozik04/nextion#17]
I'm trying to monitor a particular touch button event & am not sure how to do that from the examplar code:

```
def event_handler(type_, data):
    if type_ == EventType.STARTUP:
        print('We have booted up!')
    elif type_ == EventType.TOUCH:
        print('A button (id: %d) was touched on page %d' % (data.component_id, data.page_id))

    logging.info('Event %s data: %s', type, str(data))

```
Any ideas on how to go about this?

**Comment by yozik04** [comment]
When you touch what message it prints?
it will give you info what to expect in page and touched element id.

**Comment by dezfutak** [comment]
I want to be able to continually monitor whether or not a button has been pressed.

Doing something like:

`thisbutton=data,component_id`

from within the event_handler function

...is fine, but I want to then monitor such button touches from the async def run() function so that I can continuously monitor button presses; what's a way to do that?

**Comment by yozik04** [comment]
Do not understand what you mean. Describe the use case.

**Comment by dezfutak** [comment]
> Do not understand what you mean. Describe the use case.

No worries - figured it out in a completely different way in the end. 

Many thanks for replying!
