### ISSUE TITLE
Reading negative integer value from variable

### ISSUE THREAD

**Issue by Chronocento** [yozik04/nextion#21]
Hi, it's me again :)
I'm having some troubles reading a negative integer from a variable: if it's ≥0, I can get its value no problem, but with, for example, -1, this is what I get:

> (<class 'nextion.exceptions.CommandFailed'>, CommandFailed("Unknown response code 0x71 for command: 'get varUTC.val'",), <traceback object at 0x75684a30>)
> Unknown data received: b'ff7102000000'
> (<class 'TypeError'>, TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",), <traceback object at 0x756864e0>)

Any clue?
Thanks!

**Comment by yozik04** [comment]
Hi, what lib version?

**Comment by yozik04** [comment]
Related to #18

**Comment by Chronocento** [comment]
Sorry, didn't notice the new release!
I'll try and report back, but I'm quite sure that it will be solved with the update, sorry!

**Comment by Chronocento** [comment]
Works perfectly with 1.7.1, sorry for having bothered you!
